#spring.application.name=ecom_application
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#management.endpoints.web.exposure.include=*
#endpoint.health.show-details=always
spring:
  application:
    name: "ecom_application"

  datasource:
    url: jdbc:postgresql://localhost:5432/postgresdb
    username: postgres
    password: postgres
    hikari:
      connection-init-sql: SET TIME ZONE 'UTC'
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  #  h2:
  #    console:
  #      enabled: true
  #  datasource:
  #    url: "jdbc:h2:mem:test"
  #  jpa:
  #    show-sql: true
  #    hibernate:
  #      ddl-auto: create

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true
  info:
    env:
      enabled: true

server:
  shutdown: graceful

info:
  app:
    name: MyNewApp
    description: App built by us
    version: 1.0.0